### ISSUE TITLE
PB issue

### ISSUE THREAD

**Issue by Metalit** [Metalit/bsq-qounters-minus#3]
It's also broken for me. On any new song (that doesn't have a PB set) it shows a value about double of what it should be (19x%) and then when I replay that song the color never changes as the current score never gets any better than what's saved. This is on Quest 2 running 1.27.0

_Originally posted by @d0rh4ns in https://github.com/Metalit/bsq-qounters-minus/issues/2#issuecomment-1472896011_

Is there a saved PB or not?

**Comment by HannesK-ME** [comment]
Let me elaborate:

When I first play a song (no PB saved) the PB counter starts rising as I play, but it does so way too fast and reaches way over 100% by the end of the song (more than double of what it should show ~19x%).

When I then go to play that same song again (now that 19x% has been saved as a PB apparently) the counter never changes color to show that I'm doing better (even when I am doing better than the actual percentage I did last time) since the saved value is over 100%.

Hope this makes more sense now :)

**Comment by Metalit** [comment]
Do you have score percentage or beatleader (or ideally both)? What do they say the percentage of your PB is?

**Comment by Metalit** [comment]
This was likely caused by the issue with CustomJsonData, and even if it wasn't, the lack of response means I would probably close this anyway.

**Comment by HannesK-ME** [comment]
Apologies for the lack of reply. I had lost track of this. The value is also shown wrong on score percentage after the song is completed but beatleader shows the correct score. While I'm playing the song the current score shows correctly. Can you elaborate on the CustomJsonData issue? Or what could potentially cause this issue?
