### ISSUE TITLE
Notes Remaining and Personal Best qounters are incorrect

### ISSUE THREAD

**Issue by Holioptic** [Metalit/bsq-qounters-minus#4]
When playing any map, including the test map, the Notes Remaining shows much less notes than the map has, causing it to go negative when it reaches 0 and the map still has notes.

**Comment by Metalit** [comment]
This is unfortunately an issue with the CustomJsonData mod, not Qounters. I'll leave this open while it still exists though. (It also similarly exists with the PB qounter.)

**Comment by L3Home** [comment]
Just to clarify (though I'm sure you've noticed this), the Notes Remaining counter begins at one half the actual number of notes (rounded when an odd number). Halfway through the song, it reaches zero, so that it ends with a negative number for the remaining half of the notes.

Is there any other way to call the correct value from another source at this time, or is that library the only one that returns that count? Don't suppose it would be worth a cheap hack such as taking that value and multiplying by 2, at least until it's resolved in the library?

**Comment by Metalit** [comment]
I'm not sure if it's been "officially" released yet, but as the fixed CustomJsonData mod has been being distributed in the [BSMG discord](https://discord.gg/beatsabermods) for quite a while now, I'm going to close this
